# Generated by Django 4.1.13 on 2025-04-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=50)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('numero_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_radicado', models.DateTimeField(auto_now_add=True)),
                ('tipo_radicado', models.CharField(choices=[('Petición', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=25)),
                ('comentarios', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('cliente', models.OneToOneField(db_column='numero_identificacion', on_delete=django.db.models.deletion.CASCADE, to='core.cliente', to_field='numero_identificacion')),
            ],
        ),
    ]
