# Generated by Django 5.1.7 on 2025-04-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
