# Generated by Django 4.1.13 on 2025-04-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_codigo_verificacion_cliente_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_asignados', to='core.empleado'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('En Proceso', 'En Proceso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='En Proceso', max_length=20),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='justificacion_del_estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
