# Generated by Django 5.1.7 on 2025-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pqrs_empleado_asignado_pqrs_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en-proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo_radicado',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=25),
        ),
    ]
