# Generated by Django 5.2.12 on 2026-04-22 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_logerror_solicitudvendedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvendedor',
            name='tipo_persona',
            field=models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=10),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PETICION', 'Peticion'), ('QUEJA', 'Queja'), ('RECLAMO', 'Reclamo'), ('SUGERENCIA', 'Sugerencia')], max_length=12)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('RADICADA', 'Radicada'), ('EN_GESTION', 'En Gestion'), ('RESPONDIDA', 'Respondida'), ('CERRADA', 'Cerrada')], default='RADICADA', max_length=12)),
                ('ruta_estados', models.CharField(default='RADICADA', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.pqrs')),
            ],
        ),
    ]
