# Estados de la Solicitud de Vendedor
ESTADO_SOLICITUD_PENDIENTE = 'PENDIENTE'
ESTADO_SOLICITUD_RECHAZADA = 'RECHAZADA'
ESTADO_SOLICITUD_DEVUELTA  = 'DEVUELTA'
ESTADO_SOLICITUD_APROBADA  = 'APROBADA'

# Estados del Vendedor (Suscripción)
ESTADO_VENDEDOR_ACTIVO    = 'ACTIVA'
ESTADO_VENDEDOR_MORA      = 'EN MORA'
ESTADO_VENDEDOR_CANCELADO = 'CANCELADA'

# Tipos de Persona
TIPO_PERSONA_NATURAL  = 'NATURAL'
TIPO_PERSONA_JURIDICA = 'JURIDICA'

# Planes de Suscripción
PLAN_MENSUAL   = 'MENSUAL'
PLAN_SEMESTRAL = 'SEMESTRAL'
PLAN_ANUAL     = 'ANUAL'

# Métodos de Pago
METODO_PAGO_LINEA       = 'LINEA'
METODO_PAGO_TARJETA     = 'TARJETA'
METODO_PAGO_CONSIGNACION = 'CONSIGNACION'

# Calificaciones de Centrales de Riesgo
SCORE_ALTA       = 'ALTA'
SCORE_BAJA       = 'BAJA'
SCORE_ADVERTENCIA = 'ADVERTENCIA'

# Antecedentes Judiciales
ANTECEDENTES_REQUERIDO    = 'REQUERIDO'
ANTECEDENTES_NO_REQUERIDO = 'NO REQUERIDO'

# Estados de Pedido
PEDIDO_ESTADO_PENDIENTE = 'PENDIENTE'
PEDIDO_ESTADO_PAGADO    = 'PAGADO'

# Configuración del Negocio
IVA_ESTANDAR = 0.19
CALIFICACION_MIN_PROMEDIO = 5.0
CALIFICACION_MAX_BAJAS = 10
UMBRAL_CALIFICACION_NEGATIVA = 3
